apiVersion: apps/v1
kind: Deployment
metadata:
  name: zd-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: zd-api
  template:
    metadata:
      labels:
        app: zd-api
    spec:
      containers:
      - name: zd-api
        image: rushikesh611/zerodowntime-api:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: zd-api-secrets
              key: PORT
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: zd-api-secrets
              key: SESSION_SECRET
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: zd-api-secrets
              key: DATABASE_URL
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: zd-api-secrets
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: zd-api-secrets
              key: GITHUB_CLIENT_SECRET
        - name: GITHUB_CALLBACK_URL
          valueFrom:
            secretKeyRef:
              name: zd-api-secrets
              key: GITHUB_CALLBACK_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: zd-api-secrets
              key: JWT_SECRET
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: zd-api-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: zd-api-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: EMAIL_SOURCE
          valueFrom:
            secretKeyRef:
              name: zd-api-secrets
              key: EMAIL_SOURCE
        - name: RESEND_API_KEY
          valueFrom:
            secretKeyRef:
              name: zd-api-secrets
              key: RESEND_API_KEY
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: zd-api-service
spec:
  type: ClusterIP
  selector:
    app: zd-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001